
### DB ###
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dunzi-database.c0qdci4sjpq3.ap-northeast-2.rds.amazonaws.com/dunzi
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update #create, create-drop, none, update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # set DB column name by snake case
    show-sql: true
    generate-ddl: true

  ### DB initialize auto insert ###
  sql:
    init:
      mode: always
      encoding: utf-8
      # data-locations: "classpath: data.sql" #use different file for initializing data